### ISSUE TITLE
Ehcache java.lang.reflect.InaccessibleObjectException Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @2cd76f31

### ISSUE THREAD

**Issue by georgemayrin** [ehcache/sizeof#69]
( ehcache version org.ehcache:ehcache:3.9.9 java 11) 
WARN 8418 --- [nio-8080-exec-2] org.ehcache.sizeof.ObjectGraphWalker     : The JVM is preventing Ehcache from accessing the subgraph beneath 'private final byte[] java.lang.String.value' - cache sizes may be underestimated as a result

CacheConfiguration<String,CachedValueWrapper> cacheConfiguration= CacheConfigurationBuilder
                .newCacheConfigurationBuilder(String.class, CachedValueWrapper.class,
                        newResourcePoolsBuilder().heap(100, MemoryUnit.MB))
                .withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.parse("PT30S")))
                .build();
                
I am new to caching and was wondering if this is due to insufficient space in the heap memory?

**Comment by chrisdennis** [comment]
This is due to the more recent JVMs enforcing strong encapsulation and preventing reflective access to JVM internals. You'll need to either open up reflective access using (potentially numerous) `--add-opens` command line switches, or move to using a count based heap resource (e.g. `heap(10000)`) so that Ehcache doesn't need to size the cached elements.
